This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./template.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file template.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file template.acr....done (6 lines written, 0 warnings).
Output written in template.acr.
Transcript written in template.alg.
